name: Create a Custom action

on:
  pull_request:
    branches: [ test_github_actions ]

env:
  DOCKERHUB_USERNAME: joshinikhil27
  IMAGE_NAME: docker_image_fast_api
  DOCKERHUB_PASSWORD: Docker@123

jobs:
  checkout code and login to docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}
